// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actiontype.proto

package com.sh.yhby.protobuf;

public final class ActionTypeProbuf {
  private ActionTypeProbuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code protobuf.ActionType}
   */
  public enum ActionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PING = 1;</code>
     */
    PING(0, 1),
    /**
     * <code>LOGIN = 2;</code>
     */
    LOGIN(1, 2),
    /**
     * <code>RESPONSE = 3;</code>
     */
    RESPONSE(2, 3),
    /**
     * <code>SEND_MESSAGE = 4;</code>
     */
    SEND_MESSAGE(3, 4),
    /**
     * <code>RECEIVE_MESSAGE = 5;</code>
     */
    RECEIVE_MESSAGE(4, 5),
    /**
     * <code>RECEIVED_MESSAGE_ACK = 6;</code>
     */
    RECEIVED_MESSAGE_ACK(5, 6),
    /**
     * <code>SENDED_MESSAGE_ACK = 7;</code>
     */
    SENDED_MESSAGE_ACK(6, 7),
    ;

    /**
     * <code>PING = 1;</code>
     */
    public static final int PING_VALUE = 1;
    /**
     * <code>LOGIN = 2;</code>
     */
    public static final int LOGIN_VALUE = 2;
    /**
     * <code>RESPONSE = 3;</code>
     */
    public static final int RESPONSE_VALUE = 3;
    /**
     * <code>SEND_MESSAGE = 4;</code>
     */
    public static final int SEND_MESSAGE_VALUE = 4;
    /**
     * <code>RECEIVE_MESSAGE = 5;</code>
     */
    public static final int RECEIVE_MESSAGE_VALUE = 5;
    /**
     * <code>RECEIVED_MESSAGE_ACK = 6;</code>
     */
    public static final int RECEIVED_MESSAGE_ACK_VALUE = 6;
    /**
     * <code>SENDED_MESSAGE_ACK = 7;</code>
     */
    public static final int SENDED_MESSAGE_ACK_VALUE = 7;


    public final int getNumber() { return value; }

    public static ActionType valueOf(int value) {
      switch (value) {
        case 1: return PING;
        case 2: return LOGIN;
        case 3: return RESPONSE;
        case 4: return SEND_MESSAGE;
        case 5: return RECEIVE_MESSAGE;
        case 6: return RECEIVED_MESSAGE_ACK;
        case 7: return SENDED_MESSAGE_ACK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ActionType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
            public ActionType findValueByNumber(int number) {
              return ActionType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.sh.yhby.protobuf.ActionTypeProbuf.getDescriptor().getEnumTypes().get(0);
    }

    private static final ActionType[] VALUES = values();

    public static ActionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ActionType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protobuf.ActionType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020actiontype.proto\022\010protobuf*\210\001\n\nActionT" +
      "ype\022\010\n\004PING\020\001\022\t\n\005LOGIN\020\002\022\014\n\010RESPONSE\020\003\022\020" +
      "\n\014SEND_MESSAGE\020\004\022\023\n\017RECEIVE_MESSAGE\020\005\022\030\n" +
      "\024RECEIVED_MESSAGE_ACK\020\006\022\026\n\022SENDED_MESSAG" +
      "E_ACK\020\007B(\n\024com.sh.yhby.protobufB\020ActionT" +
      "ypeProbuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
